Feature/pass info
dstjohniii/ms-advisor pull request #53
Opened 2021-11-02 02:10 UTC by gwallace04

2021-11-02 20:46 UTC, dstjohniii requested changes
remove the uneeded comments. wrap your debugs in some sort of if-dev thing or remove them.

2021-11-02 20:46 UTC, dstjohniii commented on client/src/components/AdvisorRouter.js
> +  //Not crazy about this name, willing to change
seems fine to me, we all suck at naming. my first thought was questionState.

2021-11-02 20:46 UTC, dstjohniii commented on client/src/components/Planner/Planner.js
> +  }, [courseState]);
we dont want this to run in a production build, so we either need to check if its dev or remove it from the code.

2021-11-02 20:46 UTC, dstjohniii commented on client/src/components/Questions/QuestionTabs.js
> +export default function QuestionTabs(params) {
if there are only 2 props, we could just deconstruct.

2021-11-02 20:46 UTC, dstjohniii commented on client/src/components/Questions/Tabs/CompletedCourses.js
> +  }, [params.courseState]);
need to figure out how to not have this in a production build.

2021-11-02 20:46 UTC, dstjohniii commented on client/src/components/Questions/Tabs/CompletedCourses.js
> +      //If there's a fancy way of doing this, please change it
idk of a better way to do this, but if we cant think of one might want to remove the comments

2021-11-03 16:27 UTC, gwallace04 commented on client/src/components/AdvisorRouter.js
> +  //Not crazy about this name, willing to change
Renamed to `tabInfo` and `setTabInfo` This is more descriptive

2021-11-03 16:28 UTC, gwallace04 commented on client/src/components/Questions/Tabs/CompletedCourses.js
> +  }, [params.courseState]);
Added a conditional statement. I can't fully test it since we don't have a production build, but if I change the name to something other than "development" the object is not logged in the console.

2021-11-03 16:29 UTC, gwallace04 commented on client/src/components/Questions/Tabs/CompletedCourses.js
> +      //If there's a fancy way of doing this, please change it
I'll leave the comments until we either find a slicker way or decide this is the best approach.

2021-11-03 16:33 UTC, dstjohniii approved these changes

2021-11-03 16:35 UTC, merged