Add files via upload
dstjohniii/ms-advisor pull request #69
Opened 2021-11-18 23:37 UTC by ashwinspencer

If this gets approved, I can add whatever description is necessary.

2021-11-20 17:24 UTC, dstjohniii requested changes
I don't understand, why are these at the root of the project and not in the client. also, how is this supposed to work, you aren't editing any of the existing files?

2021-11-20 17:35 UTC, ashwinspencer commented
Sorry to hear that it didn't work.  It does work on my platform.  Most
likely reason for not working is that I didn't do Git Push from my computer
and simply uploaded the files.  Based on my past experience, I keep getting
conflicts that are very tricky to resolve. We can have a Zoom meeting and I
can show you that it works.  The other option is to push it in a way that
doesn't lead to conflicts.  What do you suggest?  Thank you.

On Sat, Nov 20, 2021 at 11:25 AM dstjohniii ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> I don't understand, why are these at the root of the project and not in
> the client. also, how is this supposed to work, you aren't editing any of
> the existing files?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dstjohniii/ms-advisor/pull/69#pullrequestreview-811845874>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANZIKSC3VMYRXLIW67VU6X3UM7KXHANCNFSM5IK3HFDQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-20 18:31 UTC, dstjohniii commented
I merged your code into main but I'm still confused, this is for instructions on the planner page so why is it in waived classes?

2021-11-20 18:36 UTC, ashwinspencer commented
I get it now.  Sorry for the confusion.  I will remove it from there and
put it on the Instructions page and then create another PR.

On Sat, Nov 20, 2021 at 12:31 PM dstjohniii ***@***.***>
wrote:

> I merged your code into main but I'm still confused, this is for
> instructions on the planner page so why is it in waived classes?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dstjohniii/ms-advisor/pull/69#issuecomment-974692162>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANZIKSEJY5W5LKMNKTD33NLUM7SQTANCNFSM5IK3HFDQ>
> .
>
>
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-20 18:37 UTC, dstjohniii commented
just checkout this branch and commit the changes here and it will automatically update this pr

2021-11-21 01:55 UTC, ashwinspencer commented
When you say "this branch", do you mean *origin/page_modal*?

On Sat, Nov 20, 2021 at 12:37 PM dstjohniii ***@***.***>
wrote:

> just checkout this branch and commit the changes here and it will
> automatically update this pr
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dstjohniii/ms-advisor/pull/69#issuecomment-974693038>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANZIKSEFO6UOJCBRQV4XFQLUM7TGXANCNFSM5IK3HFDQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-21 14:28 UTC, dstjohniii commented
yes

2021-11-21 15:53 UTC, ashwinspencer commented
Thanks.  I was able to checkout that branch and the app ran fine, but I am
now seeing the detached head message.
[image: image.png]


On Sun, Nov 21, 2021 at 8:29 AM dstjohniii ***@***.***> wrote:

> yes
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dstjohniii/ms-advisor/pull/69#issuecomment-974827410>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANZIKSFGH6KLHOKZRF4AZ7TUND627ANCNFSM5IK3HFDQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-21 16:09 UTC, ashwinspencer commented
* (HEAD detached at origin/page_modal)

On Sun, Nov 21, 2021 at 9:53 AM Ashwin Spencer ***@***.***>
wrote:

> Thanks.  I was able to checkout that branch and the app ran fine, but I am
> now seeing the detached head message.
> [image: image.png]
>
>
> On Sun, Nov 21, 2021 at 8:29 AM dstjohniii ***@***.***>
> wrote:
>
>> yes
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/dstjohniii/ms-advisor/pull/69#issuecomment-974827410>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ANZIKSFGH6KLHOKZRF4AZ7TUND627ANCNFSM5IK3HFDQ>
>> .
>> Triage notifications on the go with GitHub Mobile for iOS
>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>> or Android
>> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>>
>>
>

2021-11-22 01:44 UTC, ashwinspencer commented
I have moved the modal from Waived Courses to Instructions page.  Should I
decide on the content for the modal or do you guys have some feedback?
Thanks.

On Sun, Nov 21, 2021 at 8:29 AM dstjohniii ***@***.***> wrote:

> yes
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dstjohniii/ms-advisor/pull/69#issuecomment-974827410>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANZIKSFGH6KLHOKZRF4AZ7TUND627ANCNFSM5IK3HFDQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-23 23:58 UTC, dstjohniii commented
the ticket specifies on the planner page. and yeah just set what ever for how to use the application.

2021-11-24 02:43 UTC, ashwinspencer commented
Thank you.  Will do.

On Tue, Nov 23, 2021 at 5:58 PM dstjohniii ***@***.***> wrote:

> the ticket specifies on the planner page. and yeah just set what ever for
> how to use the application.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dstjohniii/ms-advisor/pull/69#issuecomment-977298120>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANZIKSG4XQ3UVEJ4TDMP6U3UNQTCZANCNFSM5IK3HFDQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2025-02-19 09:20 UTC, closed without merging