Display checklist
dstjohniii/ms-advisor pull request #72
Opened 2021-11-30 02:57 UTC by gwallace04

Display the checklist on the planner page. There are probably some weird bugs that I haven't discovered yet, so let me know if you find any.

2021-11-30 21:34 UTC, dstjohniii requested changes
Mostly looks good but missing a few things needed to hit the minimum requirements. Also it looks like you aren't using prettier, its a super simple plugin that could clean up the formatting of your code.
biggest miss is not having a 6000 level requirement.

2021-11-30 21:34 UTC, dstjohniii commented on client/src/components/Planner/Checklist.js
> +				Total credit hours: {getTotalCreditHours()} / 30
this might be better somewhere we could easily configure the 30 required credit hours, like a static variable atleast.

2021-11-30 21:34 UTC, dstjohniii commented on client/src/components/Planner/DisplayList.js
> +							props.tabInfo.completed.includes(a) || props.plannedCourses.includes(a);
This should include waived and restricted classes.

2021-11-30 21:34 UTC, dstjohniii commented on client/src/components/Planner/Checklist.js
> +    const total = tabInfo.completed.length + plannedCourses.length;
This should include transfer credits added to the sum.

2021-11-30 21:34 UTC, dstjohniii commented on client/src/components/Planner/Checklist.js
> +  function is6000Satisfied() {
This is never used, we should be checking this.

2021-11-30 21:34 UTC, dstjohniii commented on client/src/components/Planner/Checklist.js
> +import List from "@mui/material/List"
not used remove

2021-11-30 21:34 UTC, dstjohniii commented on client/src/components/Planner/Checklist.js
> +import { ListItem, ListItemText, ListSubheader, Typography } from "@mui/material";
only typography is used here remove the others.

2021-11-30 21:34 UTC, dstjohniii commented on client/src/components/Planner/Checklist.js
> +        width: 300,
change width to 310, Artificial Intelligence Certificate is too long and wraps at a weird point

2021-11-30 21:34 UTC, dstjohniii commented on client/src/components/Planner/Checklist.js
> +        console.log(c, reqCourses, eleCourses);
do we need this?

2021-11-30 21:34 UTC, dstjohniii commented on client/src/components/Planner/Planner.js
> +  console.log("csvDataPlanner: ", csvData);
do we need this?

2021-11-30 21:34 UTC, dstjohniii commented on client/src/components/Planner/DisplayList.js
> +import { useState } from "react";
Clean up unused imports

2021-12-01 00:11 UTC, gwallace04 commented on client/src/components/Planner/Checklist.js
> +				Total credit hours: {getTotalCreditHours()} / 30
I created a const TOTAL_CREDIT_HOURS after the import statements in the checklist file. If we find there are other global static variables we'd like to use, we can move them all to a separate file.

2021-12-01 00:12 UTC, gwallace04 commented on client/src/components/Planner/DisplayList.js
> +							props.tabInfo.completed.includes(a) || props.plannedCourses.includes(a);
Added waived courses to the check. Restricted courses will never be in the required/elective courses for any of the certificates or core classes.

2021-12-01 00:12 UTC, gwallace04 commented on client/src/components/Planner/Checklist.js
> +    const total = tabInfo.completed.length + plannedCourses.length;
Done, added

2021-12-01 00:12 UTC, gwallace04 commented on client/src/components/Planner/Checklist.js
> +import List from "@mui/material/List"
Done

2021-12-01 00:13 UTC, gwallace04 commented on client/src/components/Planner/Checklist.js
> +        width: 300,
Making it 310 looked weird as it's slightly wider than the other rectangle (the course picker). I removed the word "Certificate" when displaying a certificate, and all of them fit.

2021-12-01 00:14 UTC, gwallace04 commented on client/src/components/Planner/Checklist.js
> +        console.log(c, reqCourses, eleCourses);
Removed

2021-12-01 00:14 UTC, gwallace04 commented on client/src/components/Planner/Planner.js
> +  console.log("csvDataPlanner: ", csvData);
Removed

2021-12-01 00:14 UTC, gwallace04 commented on client/src/components/Planner/DisplayList.js
> +import { useState } from "react";
Removed

2021-12-01 00:30 UTC, dstjohniii approved these changes
LGTM

2021-12-01 00:33 UTC, merged